/**
 * @fileoverview Consolidated Hero Icons using factory pattern
 * @description Auto-generated from icon-paths.ts - DO NOT EDIT MANUALLY
 * @version 2.0.0 - Codegen implementation
 * @module shared/components/ui/Icon/hero
 *
 * Generated by: scripts/generate-hero-icons.ts
 * Source: src/shared/components/ui/Icon/hero/icon-paths.ts
 *
 * Consolidation benefits:
 * - Automated icon generation from source of truth
 * - Single point of maintenance (icon-paths.ts)
 * - Tree-shakable exports
 * - Consistent naming and structure
 */

import { Icon, type IconProps } from '@shared/components/ui/Icon/Icon';
import type { JSXElement } from '@shared/external/vendors';
import { For } from 'solid-js';

import {
  type AllIconNames,
  ICON_PATHS,
  type IconName,
  MULTI_PATH_ICONS,
  type MultiPathIconName,
} from './icon-paths';

// Re-export types and paths for advanced use cases
export { type AllIconNames, ICON_PATHS, type IconName, MULTI_PATH_ICONS, type MultiPathIconName };

/**
 * Create a single-path icon component
 * @param name - Icon name from ICON_PATHS
 * @returns Icon component function
 */
function createSinglePathIcon(name: IconName): (props: IconProps) => JSXElement {
  return function IconComponent(props: IconProps): JSXElement {
    return (
      <Icon {...props}>
        <path d={ICON_PATHS[name]} />
      </Icon>
    );
  };
}

/**
 * Create a multi-path icon component
 * @param name - Icon name from MULTI_PATH_ICONS
 * @returns Icon component function
 */
function createMultiPathIcon(name: MultiPathIconName): (props: IconProps) => JSXElement {
  return function IconComponent(props: IconProps): JSXElement {
    return (
      <Icon {...props}>
        <For each={MULTI_PATH_ICONS[name]}>
          {(pathData: string) => <path d={pathData} />}
        </For>
      </Icon>
    );
  };
}

// ============================================================================
// Single-Path Icons (auto-generated)
// ============================================================================

/** Download icon (single-path) */
export const HeroDownload = createSinglePathIcon('download');

/** ArrowSmallLeft icon (single-path) */
export const HeroArrowSmallLeft = createSinglePathIcon('arrowSmallLeft');

/** ArrowSmallRight icon (single-path) */
export const HeroArrowSmallRight = createSinglePathIcon('arrowSmallRight');

/** ArrowsPointingIn icon (single-path) */
export const HeroArrowsPointingIn = createSinglePathIcon('arrowsPointingIn');

/** ArrowsPointingOut icon (single-path) */
export const HeroArrowsPointingOut = createSinglePathIcon('arrowsPointingOut');

/** ArrowsRightLeft icon (single-path) */
export const HeroArrowsRightLeft = createSinglePathIcon('arrowsRightLeft');

/** ArrowsUpDown icon (single-path) */
export const HeroArrowsUpDown = createSinglePathIcon('arrowsUpDown');

/** ArrowDownOnSquareStack icon (single-path) */
export const HeroArrowDownOnSquareStack = createSinglePathIcon('arrowDownOnSquareStack');

/** ArrowLeftOnRectangle icon (single-path) */
export const HeroArrowLeftOnRectangle = createSinglePathIcon('arrowLeftOnRectangle');

/** ChatBubbleLeftRight icon (single-path) */
export const HeroChatBubbleLeftRight = createSinglePathIcon('chatBubbleLeftRight');

// ============================================================================
// Multi-Path Icons (auto-generated)
// ============================================================================

/** Cog6Tooth icon (multi-path) */
export const HeroCog6Tooth = createMultiPathIcon('cog6Tooth');
