import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

import { logger } from '@shared/logging';

const PROJECT_ROOT = process.cwd();
const TOKEN_SOURCE_FILES = [
  path.join(PROJECT_ROOT, 'src', 'shared', 'styles', 'design-tokens.primitive.css'),
  path.join(PROJECT_ROOT, 'src', 'shared', 'styles', 'design-tokens.semantic.css'),
  path.join(PROJECT_ROOT, 'src', 'shared', 'styles', 'design-tokens.component.css'),
];
const OUTPUT_FILE = path.join(
  PROJECT_ROOT,
  'src',
  'shared',
  'types',
  'generated',
  'design-token-names.ts'
);

const TOKEN_DEFINITION_REGEX = /(--[a-z0-9-]+)\s*:/gi;

async function extractTokens(filePath: string): Promise<Set<string>> {
  const content = await fs.readFile(filePath, 'utf8');
  const matches = content.matchAll(TOKEN_DEFINITION_REGEX);
  const tokens = new Set<string>();

  for (const match of matches) {
    if (match[1]) {
      tokens.add(match[1]);
    }
  }

  return tokens;
}

function buildFileContent(tokens: string[]): string {
  const entries = tokens.map(token => `  '${token}',`).join('\n');
  return `/**
 * @fileoverview Auto-generated list of design token CSS variable names.
 * @generated by scripts/generate-design-token-types.ts — Do not edit manually.
 */

export const DESIGN_TOKEN_NAMES = [
${entries}
] as const;

export type DesignTokenName = (typeof DESIGN_TOKEN_NAMES)[number];
`;
}

async function ensureOutputDirectory(): Promise<void> {
  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
}

async function main(): Promise<void> {
  const tokenSets = await Promise.all(TOKEN_SOURCE_FILES.map(extractTokens));
  const combined = new Set<string>();
  tokenSets.forEach(set => {
    set.forEach(token => combined.add(token));
  });

  const sortedTokens = [...combined].sort((a, b) => a.localeCompare(b));

  await ensureOutputDirectory();
  await fs.writeFile(OUTPUT_FILE, buildFileContent(sortedTokens), 'utf8');

  logger.info('[tokens:types] Generated design token definitions', {
    count: sortedTokens.length,
    output: OUTPUT_FILE,
  });
}

main().catch(error => {
  logger.error('[tokens:types] Failed to generate token definitions', error);
  process.exitCode = 1;
});
