# Composite Action: Deno Environment Setup
# Responsibility: Reusable setup for all workflows
# - Deno installation with version consistency
# - Dependency cache configuration
# - Node modules setup for npm compatibility

name: "Setup Deno Environment"
description: "Setup Deno with cache and dependencies"

inputs:
  deno-version:
    description: "Deno version to use"
    required: false
    default: "2.x"
  working-directory:
    description: "Working directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: 🦕 Setup Deno ${{ inputs.deno-version }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno-version }}

    - name: 📦 Cache Deno dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/deno
          ${{ inputs.working-directory }}/node_modules
        key: deno-${{ runner.os }}-${{ hashFiles('**/deno.lock', '**/deno.json') }}
        restore-keys: |
          deno-${{ runner.os }}-

    - name: 📥 Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Deno will auto-install npm dependencies via nodeModulesDir
        deno cache --node-modules-dir=auto src/main.ts 2>/dev/null || true
