name: Auto Release

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'vite.config.ts'
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease

env:
  NODE_VERSION: '20'

jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for version changes
        id: check
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          # Get latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LATEST_VERSION=${LATEST_TAG#v}

          echo "Current version: $CURRENT_VERSION"
          echo "Latest version: $LATEST_VERSION"

          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

  auto-release:
    name: Auto Release
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.should_release == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Quality Check
        run: npm run quality

      - name: Comprehensive Validation
        run: npm run validate:comprehensive

      - name: Bump version
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          git add package.json package-lock.json
          git commit -m "chore: bump version to v$NEW_VERSION"
          git push

      - name: Get version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build release
        run: npm run build

      - name: Commit dist files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/xcom-enhanced-gallery.user.js
          git diff --staged --quiet || git commit -m "build: update dist for release v${{ steps.version.outputs.version }} [skip ci]"
          git push

      - name: Create release package
        run: npm run package

      - name: Generate checksums
        run: |
          cd release
          sha256sum *.js > checksums.txt
          cat checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: X.com Enhanced Gallery v${{ steps.version.outputs.version }}
          body: |
            # X.com Enhanced Gallery v${{ steps.version.outputs.version }}
            
            트위터(X) 미디어 뷰어와 다운로드 기능을 향상시키는 유저스크립트입니다.
            
            ## 🚀 빠른 설치
            
            **원클릭 설치:** [xcom-enhanced-gallery.user.js](https://github.com/PiesP/xcom-enhanced-gallery/raw/v${{ steps.version.outputs.version }}/dist/xcom-enhanced-gallery.user.js) 클릭
            
            > 유저스크립트 매니저(Tampermonkey, Greasemonkey 등)가 설치되어 있어야 합니다.
            
            ## 📦 수동 설치
            
            1. 아래 Assets에서 `xcom-enhanced-gallery.user.js` 파일 다운로드
            2. 유저스크립트 매니저에서 파일 설치
            3. X.com 방문하여 향상된 갤러리 기능 사용
            
            ## ✨ 주요 기능
            
            - 🖼️ 향상된 미디어 갤러리 뷰어
            - ⬇️ 원클릭 미디어 다운로드
            - 🔍 이미지/비디오 확대 및 탐색
            - ⚡ 빠른 키보드 단축키 지원
          files: |
            release/xcom-enhanced-gallery.user.js
            release/checksums.txt
            dist/xcom-enhanced-gallery.user.js
          draft: false
          prerelease: false
          make_latest: true
